services:
  - type: web
    name: kubra-market-admin
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: kubra-market-db
          property: connectionString

databases:
  - name: kubra-market-db
    plan: free
    postDeploySchemaScripts:
      - npx drizzle-kit push